# İmport Etme

In [1]:
import numpy as np

# Vektör Oluşturma

np.array ile 1xN veya Nx1 gibi vektörler oluşturulabilir.

In [3]:
satir_vektor = np.array([3,2,1])
print(satir_vektor)

[3 2 1]


In [4]:
sutun_vektor = np.array([[10],[20],[30]])
print(sutun_vektor)

[[10]
 [20]
 [30]]


# Matris (Matrix) Oluşturma

np.array ile NxM boyutlu matrisler oluşturulabilir.

In [6]:
matris = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(matris)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


np.zeros ile verilen boyut veri türüne göre sıfır matris oluşturulur.

In [7]:
sifir_matris = np.zeros([3,4] , dtype = float)
print(sifir_matris)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


np.ones ile verilen boyut ve veri türüne göre elemanları birlerden oluşan matris oluşturulur.

In [8]:
bir_matris = np.ones([3,4] , dtype = int)
print(bir_matris)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


np.eye fonksiyonu ile verilen boyut ve veri türü ile birim matris oluşturulur.

In [9]:
birim_matris = np.eye(5 , dtype = int)
print(birim_matris)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


# Matrislerde Matematiksel İşlemler

In [10]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[7,5],[8,9]])

np.add fonksiyonu matrislerin eşdeğer pozisyondaki elemanlarını aynı kutucukta toplar.

In [11]:
toplama = np.add(matrix1 , matrix2)
print(toplama)

[[ 8  7]
 [11 13]]


np.subtract fonksiyonu matrislerin eşdeğer pozisyondaki elemanlarını aynı kutucukta çıkarır.

In [12]:
cikarma = np.subtract(matrix1 , matrix2)
print(cikarma)

[[-6 -3]
 [-5 -5]]


matris1 * matris2 işlemi ise matrislerin eşdeğer pozisyonundaki elemanlarını aynı kutucukta çarpar. Matris çarpımı ile aynı şey değillerdir.

In [13]:
carpim = matrix1 * matrix2
print(carpim)

[[ 7 10]
 [24 36]]


# Matrislerde Min, Max, Ortalama, Toplam, Varyans ve Standart Sapma Bulma

In [14]:
matrix = np.array([[2,4,6],[8,10,12],[14,16,18]])
print(matrix)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


matris.min() fonksiyonu matris içindeki en küçük elemanı bulur.

In [16]:
print("Minimum Değer: " , matrix.min())

Minimum Değer:  2


matris.max() fonksiyonu matris içindeki en büyük elemanı bulur.

In [17]:
print("Maksimum Değer: " , matrix.max())

Maksimum Değer:  18


matris.mean() fonksiyonu matris içindeki değerlerin ortalamasını bulur.

In [18]:
print("Ortalama Değer: " , matrix.mean())

Ortalama Değer:  10.0


matris.min() fonksiyonu matris içindeki elemanların toplamını bulur.

In [19]:
print("Toplam Değer: " , matrix.sum())

Toplam Değer:  90


matris.var() fonksiyonu matris içindeki değerlerin varyans değerini bulur.Varyans, bir veri kümesindeki değerlerin ortalamadan ne kadar sapma gösterdiğini ölçen istatistiksel bir değerdir.

In [20]:
print("Varyans Değer: " , matrix.var())

Varyans Değer:  26.666666666666668


matris.std() fonksiyonu matris içindeki değerlerin standart sapmasını bulur.Standart sapma, veri noktalarının ortalamadan ne kadar saptığını gösteren bir ölçüdür ve varyansın karekökü olarak hesaplanır.

In [21]:
print("Standart Sapma: " , matrix.std())

Standart Sapma:  5.163977794943222


# Reshape ve Transpose İşlemleri

reshape fonksiyonu matrisi uygun olan istenen boyutlara dönüştürür.<br>
transpose işlemi ise matrisin transpozunu alır.Transpoz, bir matrisin satır ve sütunlarının yer değiştirmesiyle elde edilen matristir.

In [22]:
matrix = np.array([[2,4],[8,10],[14,16]])
print(matrix)

[[ 2  4]
 [ 8 10]
 [14 16]]


In [23]:
print(matrix.reshape(6,1))

[[ 2]
 [ 4]
 [ 8]
 [10]
 [14]
 [16]]


In [25]:
print(matrix.reshape(1,6))

[[ 2  4  8 10 14 16]]


In [27]:
print(matrix.reshape(2,3))

[[ 2  4  8]
 [10 14 16]]


In [28]:
print(matrix.T)

[[ 2  8 14]
 [ 4 10 16]]


# Matrisin Determinantı ve Rank Bulma

In [29]:
matrix = np.array([[4,2],[10,10]])
print(matrix)

[[ 4  2]
 [10 10]]


np.linalg.det(matris) fonksiyonu matrisin determinantını bulur. Determinant, bir kare matrisin tek bir sayı ile temsil edilen özel bir özelliğidir.

In [30]:
print("Determinant: " , np.linalg.det(matrix))

Determinant:  20.000000000000007


np.linalg.matrix_rank(matris) fonksiyonu matrisin rütbesini bulur. Rank (rütbe), bir matrisin doğrusal olarak bağımsız satır veya sütunlarının sayısını belirten bir sayıdır.

In [31]:
print("Rank: " , np.linalg.matrix_rank(matrix))

Rank:  2


# Matrisin Köşegenini (Diagonel) Alma

In [32]:
matrix = np.array([[4,2,1],[5,3,2],[30,10,12]])
print(matrix)

[[ 4  2  1]
 [ 5  3  2]
 [30 10 12]]


matris.diagonal() fonksiyonu bir kare matrisin sol üstten sağ alta uzanan ana çizgisini vektör olarak verir. Kare matris şarttır.

In [33]:
print(matrix.diagonal())

[ 4  3 12]


offset değeri ise ana köşegen matrisi kaydırma parametresidir.

In [34]:
print(matrix.diagonal(offset=1))

[2 2]


In [35]:
print(matrix.diagonal(offset=-1))

[ 5 10]


# Matrisin İzini Alma (Trace of a Matrix)

matrix.trace() fonksiyonu bir matrisin ana köşegenindeki elemanların toplamını hesaplar.

In [36]:
matrix = np.array([[4,2,1],[5,3,2],[30,10,12]])
print(matrix)

[[ 4  2  1]
 [ 5  3  2]
 [30 10 12]]


In [37]:
print("Matrisin Köşegenlerinin Toplamı: " , matrix.trace())

Matrisin Köşegenlerinin Toplamı:  19


# Matrisin Özdeğerlerin (Eigenvalues) ve Özvektörlerin (Eigenvectors) Bulunması

Özdeğer, bir matrisin, belirli bir özvektörle çarpıldığında, yalnızca bir skalar ile çarpılarak kendisini değiştirmesini sağlar. Yani, bir matrisin özdeğeri, matrisin özvektörlere uygulandığında, yalnızca skalar bir çarpanla dönüşen bir değeridir.<br>
Özvektör, bir matrisin dönüşümü sırasında yönünü değiştirmeyen, yani yalnızca büyüklüğü değişen bir vektördür. Özvektörler, genellikle bir matrisin özelliklerini anlamamıza yardımcı olur.

In [39]:
matrix = np.array([[4,2,1],[5,3,2],[30,10,12]])
print(matrix)

[[ 4  2  1]
 [ 5  3  2]
 [30 10 12]]


In [40]:
print("Matrisin Köşegenlerinin Toplamı: " , matrix.trace())

Matrisin Köşegenlerinin Toplamı:  19


In [44]:
eigenvalues, eigenvectors=np.linalg.eig(matrix)
print("Özdeğerler: ")
print(eigenvalues)
print("Özvektörler: ")
print(eigenvectors)

Özdeğerler: 
[16.96089936+0.j          1.01955032+0.61281029j  1.01955032-0.61281029j]
Özvektörler: 
[[-0.10284175+0.j         -0.33519369+0.10454783j -0.33519369-0.10454783j]
 [-0.17705416+0.j          0.01759649-0.25850484j  0.01759649+0.25850484j]
 [-0.97881326+0.j          0.89976694+0.j          0.89976694-0.j        ]]


# Vektörlerin İç Çarpım (Dot Product/Inner Product)

np.dot fonksiyonu verilen 2 matrisin iç çarpımını hesaplar. İç Çarpım bu formülle bulunur : A⋅B=∣A∣⋅∣B∣⋅cos(θ) <br>
A⋅B: A ve B vektörlerinin iç çarpımı.<br>
|A| ve |B|: A ve B vektörlerinin uzunlukları (veya normları)<br>
θ: A ve B vektörleri arasındaki açı.


In [45]:
vector1 = np.array([2,4,6])
vector2 = np.array([3,5,7])
print(vector1 , end="")
print(vector2)

[2 4 6][3 5 7]


In [47]:
print("Vektörlerin İç Çarpımları: " , np.dot(vector1,vector2))

Vektörlerin İç Çarpımları:  68


# Matrisin Tersini Alma (Invert)

np.linalg.inv() fonksiyonu matrisin tersini alır. Matrisin tersi şu formülle hesaplanır: A ⋅ A⁻¹ = A⁻¹ ⋅ A = I <br>
A: Orijinal matris <br>
A⁻¹: Matrisin tersi <br>
I: Birim matris 


In [48]:
matrix = np.array([[1,3],[4,6]])
print(matrix)

[[1 3]
 [4 6]]


In [49]:
print(np.linalg.inv(matrix))

[[-1.          0.5       ]
 [ 0.66666667 -0.16666667]]
