In [1]:
import numpy as np

# Numpy (NumericPython)

Pythonda matematiksel işlemleri hızlı bir biçimde yapmamızı sağlayan kütüphanedir.

In [4]:
np_array = np.array( [1,2,3,4,5,6,7,8,9,10] )
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
%%timeit   #Timeit , alttaki hücrenin hızını hesaplar.
np_array + 1

4.16 μs ± 1.66 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
python_list = list(range(1_000_000))
np_list = np.array(python_list)

In [9]:
%%timeit
[ x+1 for x in python_list]

130 ms ± 18.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%%timeit
np_array + 1

1.7 μs ± 253 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [46]:
array1 = np.array(1)          #Tek eleman => Scalar , Satır-Sütun Matris => Vektör , NxM Matris => Matrix , Çok Boyutlu Matris Min 3 Boyut => Tensor

In [14]:
type(array1) #ndarray => n-dimensional array

numpy.ndarray

In [16]:
array1.ndim #ndim => ndimension(boyutu) = 0

0

In [18]:
array2 = np.array( [10,20,30] )
array2.ndim , array2.shape  #1D Array (Vector)

(1, (3,))

In [19]:
array3 = np.array( [40,50,60] )
array3.ndim , array3.shape

(1, (3,))

In [25]:
result = array2 + array3  #Matematiksel işlemler boyutlar uyuşurken sadece çalışır 2 Boyutlu ile 2 Boyutlu işlem gerçekleştirir.
result

array([50, 70, 90])

In [22]:
result2 = array3 - array2
result2

array([30, 30, 30])

In [24]:
array4 = np.array( [100,200] )

In [28]:
array5 = np.array(
    [
        [10,20,30],
        [40,50,60]
    ]
    
)
array5.ndim , array5.shape #2 boyutlu 2x3 matris

(2, (2, 3))

In [29]:
array6 = np.array(
    [
        [70,80,90],
        [100,110,120]
    ]
)
array6.ndim , array6.shape

(2, (2, 3))

In [33]:
result3 = array5 + array6
result3

array([[ 80, 100, 120],
       [140, 160, 180]])

## Dot Product (İç Çarpım)

In [41]:
array7 = np.array(
    [
        [10,20,30],
        [40,50,60]
    ]
)
array7.shape #Boyut 2x3

(2, 3)

In [40]:
array8 = np.array(
    [
        [10,20],
        [30,40],
        [50,60]
    ]
) 
array8.shape #Boyut 3x2

(3, 2)

In [37]:
np.dot( array7 , array8 )  #İç Çarpım bildiğimiz matris çarpımıdır. Matris Boyutları N x M ve M x K olmalı K = N olabilir. Sonuç N x K olur.

array([[2200, 2800],
       [4900, 6400]])

In [47]:
array9 = np.array(
    [
        [ [10,20] , [30,40] , [50,60] ],
        [ [70,80] , [90,100] , [110,120] ]
    ]
)
array9.ndim , array9.shape  #3 Boyutlu olduğu için Tensor ve diğer matematiksel işlemler Tesnorler içinde geçerli

(3, (2, 3, 2))

In [55]:
array10 = np.random.randint(0,255, (1500,1000))
array10

array([[173, 117,   4, ..., 221,  32, 128],
       [ 36, 138,  78, ..., 194, 182, 166],
       [ 15, 213, 182, ..., 186,  13, 148],
       ...,
       [168,  84, 234, ..., 226,  54, 132],
       [215, 190,  16, ..., 103,   8,  81],
       [ 90, 209, 117, ..., 176,  41,  18]],
      shape=(1500, 1000), dtype=int32)

## Yapay Zeka sadece numeric verilerle eğitilebildiği için eldeki bütün verileri numeric verilere çevirmemiz gerekiyor.

In [49]:
from PIL import Image

In [53]:
image = Image.open("kedi.jpg") #Resmi okuyup değişkene atadık

In [54]:
image_array = np.array(image) #Resmi numpy array çevirdik.
image_array.ndim , image_array.shape

(3, (1500, 1000, 3))

In [52]:
image_array

array([[[ 92,  87,  84],
        [ 92,  87,  84],
        [ 92,  87,  84],
        ...,
        [ 96, 101, 104],
        [ 99, 104, 107],
        [101, 106, 109]],

       [[ 92,  87,  84],
        [ 92,  87,  84],
        [ 92,  87,  84],
        ...,
        [ 96, 101, 104],
        [ 99, 104, 107],
        [101, 106, 109]],

       [[ 92,  87,  84],
        [ 92,  87,  84],
        [ 92,  87,  84],
        ...,
        [ 96, 101, 104],
        [ 99, 104, 107],
        [101, 106, 109]],

       ...,

       [[  2,   2,   4],
        [  2,   2,   4],
        [  2,   2,   4],
        ...,
        [ 35,  25,  23],
        [ 35,  25,  23],
        [ 35,  25,  23]],

       [[  2,   2,   4],
        [  2,   2,   4],
        [  2,   2,   4],
        ...,
        [ 36,  26,  24],
        [ 36,  26,  24],
        [ 36,  26,  24]],

       [[  3,   3,   5],
        [  3,   3,   5],
        [  3,   3,   5],
        ...,
        [ 37,  27,  25],
        [ 37,  27,  25],
        [ 37,  27,  25]]